[package]
name = "brc20-bridge"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
export-api = []

[dependencies]
candid = { workspace = true }
ic-canister = { workspace = true }
ic-exports = { workspace = true }
ic-metrics = { workspace = true }
ic-storage = { workspace = true }
