[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
multiline_func_header = 'params_first'
single_line_statement_blocks = "multi"
contract_new_lines = true
