[workspace]
members = [
    "src/bitfinity-benchmark",
    "src/brc20-bridge",
    "src/btc-bridge",
    "src/create_bft_bridge_tool",
    "src/erc20-minter",
    "src/inscriber",
    "src/integration-tests",
    "src/icrc2-minter",
    "src/minter-contract-utils",
    "src/solidity-helper",
    "src/spender-canister",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
bitcoin = "0.31"
candid = { version = "0.10", features = ["value"] }
clap = { version = "4", features = ["derive"] }
did = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "did", tag = "v0.16.x" }
env_logger = { version = "0.11", default-features = false }
eth-signer = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "eth-signer", tag = "v0.16.x" }
ethereum-json-rpc-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "ethereum-json-rpc-client", tag = "v0.16.x" }
ethereum-types = "0.14"
ethers-core = "2.0"
evm-canister-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "evm-canister-client", tag = "v0.16.x" }
futures = { version = "0.3", default-features = false }
hex = "0.4"
ic-btc-interface = "0.2"
ic-canister = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-canister", tag = "v0.14.x" }
ic-canister-client = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-canister-client", tag = "v0.14.x" }
ic-exports = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-exports", tag = "v0.14.x" }
ic-helpers = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-helpers", tag = "v0.14.x" }
ic-log = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-log", tag = "v0.14.x" }
ic-metrics = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-metrics", tag = "v0.14.x", features = [
    "export-api",
] }
ic-stable-structures = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-stable-structures", tag = "v0.14.x" }
ic-storage = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-storage", tag = "v0.14.x" }
ic-task-scheduler = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-task-scheduler", tag = "v0.14.x" }
ic-test-utils = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-test-utils", tag = "v0.14.x" }
jsonrpc-core = "18.0"
log = "0.4"
minter-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "minter-client", tag = "v0.16.x" }
minter-did = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "minter-did", tag = "v0.16.x" }
mockall = "0.12"
once_cell = "1.16"
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
reqwest = { version = "0.11", default-features = false }
rlp = "0.5"
serde = "1.0"
serde_json = "1.0"
signature-verification-canister-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "signature-verification-canister-client", tag = "v0.16.x" }
thiserror = "1.0"
tokio = { version = "1.36", features = ["macros", "rt"] }
vergen = { version = "8.3", default-features = false, features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[profile.dev]
debug = false

# Set the settings for all dependencies (but not this crate itself or any workspace member).
# This includes build dependencies.
# Level range is from 0 (default for dev) to 3 (default for release)
[profile.dev.package."*"]
opt-level = 2

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

[profile.release]
#opt-level = "z"
lto = true
codegen-units = 1
