[workspace]
members = ["src/inscription-canister"]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bitcoin = { version = "0.31", features = ["serde"] }
candid = "0.10"
ic-cdk = "0.12"
ord-rs = { git = "https://github.com/bitfinity-network/ord-rs.git" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev]
debug = false

# Set the settings for all dependencies (but not this crate itself or any workspace member).
# This includes build dependencies.
# Level range is from 0 (default for dev) to 3 (default for release)
[profile.dev.package."*"]
opt-level = 2

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

[profile.release]
#opt-level = "z"
lto = true
codegen-units = 1
