[workspace]
members = ["src/did", "src/inscriber"]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
async-trait = "0.1"
bitcoin = { version = "0.31", features = ["serde"] }
bs58 = "0.5"
candid = "0.10"
hex = "0.4"
ic-canister = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-canister", tag = "v0.13.x" }
ic-exports = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-exports", tag = "v0.13.x" }
ic-metrics = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-metrics", tag = "v0.13.x", features = [
    "export-api",
] }
ic-storage = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-storage", tag = "v0.13.x" }
jsonrpc-core = "18"
log = "0.4"
ord-rs = { git = "https://github.com/bitfinity-network/ord-rs.git", branch = "fix/external-signing-flow" }
ripemd = "0.1"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"
sha2 = "0.10"
thiserror = "1.0"
vergen = { version = "8.3", default-features = false, features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

# getrandom workaround
getrandom = { version = "0.2", features = ["custom"] }
rand = { version = "0.8", features = ["getrandom"] }

k256 = { version = "0.13", features = ["ecdsa"] }

[profile.dev]
debug = false

# Set the settings for all dependencies (but not this crate itself or any workspace member).
# This includes build dependencies.
# Level range is from 0 (default for dev) to 3 (default for release)
[profile.dev.package."*"]
opt-level = 2

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

[profile.release]
#opt-level = "z"
lto = true
codegen-units = 1
