[package]
name = "inscription_canister"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "inscription-canister-did"
path = "src/lib.rs"

[dependencies]
bitcoin = { workspace = true }
candid = { workspace = true }
ic-cdk = { workspace = true }
ord-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
