[package]
name = "bridge-tool"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
candid = { workspace = true }
clap = { workspace = true }
did = { workspace = true }
eth-signer = { workspace = true }
ethereum-types = { workspace = true }
ethers-core = { workspace = true }
evm-canister-client = { workspace = true, features = ["ic-agent-client"] }
ethereum-json-rpc-client = { workspace = true, features = ["reqwest"] }
hex = { workspace = true }
ic-agent = { workspace = true }
ic-canister-client = { workspace = true, features = ["ic-agent-client"] }
minter-contract-utils = { path = "../minter-contract-utils", features = [
    "test-contracts",
] }
minter-did = { workspace = true, features = ["runes"] }
rand = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
