[package]
name = "inscriber"
version.workspace = true
edition.workspace = true


[features]
export-api = []

[dependencies]
async-trait = { workspace = true }
bitcoin = { workspace = true }
bs58 = { workspace = true }
candid = { workspace = true }
did = { workspace = true }
hex = { workspace = true }
ic-canister = { workspace = true }
ic-crypto-getrandom-for-wasm = { workspace = true }
ic-exports = { workspace = true }
ic-metrics = { workspace = true }
ic-storage = { workspace = true }
log = { workspace = true }
ord-rs = { workspace = true }
getrandom = { version = "0.2", features = ["custom"] }
ripemd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[build-dependencies]
vergen = { workspace = true }
