services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bitcoind:
    image: lncm/bitcoind:v27.0
    container_name: bitcoind
    command: ["-txindex", "-regtest"]
    ports:
      - "18443:18443"
      - "18444:18444"
      # - "8333:8333"
      # - "8332:8332"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin-data:/data/.bitcoin
      - ./bitcoin.conf:/data/.bitcoin/bitcoin.conf
  ordinals-api:
    container_name: ordinals-api
    build:
      context: .
      dockerfile: ordinals-api.dockerfile
    volumes:
      - ./ordinals-api.env:/app/ordinals-api/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  ordhook:
    container_name: ordhook
    build:
      context: https://github.com/hirosystems/ordhook.git
      dockerfile: dockerfiles/components/ordhook.dockerfile
    ports:
      - "20456:20456"
    command:
      [
        "service",
        "start",
        "--post-to=http://ordinals-api:3000/api/events",
        "--auth-token=1",
        "--config-path=/Ordhook.toml",
      ]
    volumes:
      - ./Ordhook.toml:/Ordhook.toml
    depends_on:
      - bitcoind
      - ordinals-api
  ordinals-explorer:
    container_name: ordinals-explorer
    build:
      context: .
      dockerfile: ordinals-explorer.dockerfile
    env_file:
      - ./ordinals-explorer.env
    ports:
      - "1337:3001"
      - "9001:9001"
    volumes:
      - ./ordinals-explorer.env:/usr/src/ordinals-explorer/.env.production
    depends_on:
      - ordinals-api
  ord:
    container_name: ord
    build:
      dockerfile: ord.dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../brc20_json_inscriptions:/brc20_json_inscriptions
    depends_on:
      - bitcoind

volumes:
  bitcoin-data:
  db-data:
