services:
  bitcoind:
    container_name: bitcoind
    image: lncm/bitcoind:v26.0
    command: ["-txindex", "-regtest"]
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin-data:/data/.bitcoin
      - ./bitcoin.conf:/data/.bitcoin/bitcoin.conf
  ord:
    container_name: ord
    build:
      dockerfile: ord.dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../brc20_json_inscriptions:/brc20_json_inscriptions
    depends_on:
      - bitcoind
  esplora:
    container_name: esplora
    build:
      dockerfile: esplora.dockerfile
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - esplora-data:/app/esplora
    depends_on:
      - bitcoind
    environment:
      - NO_REGTEST_MINING=1

volumes:
  bitcoin-data:
  esplora-data:
