services:
  bitcoind:
    container_name: bitcoind
    image: lncm/bitcoind:v26.0
    command: ["-txindex"]
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin-data:/data/.bitcoin
      - ./bitcoin.conf:/data/.bitcoin/bitcoin.conf
  ord:
    container_name: ord
    build:
      dockerfile: ord.dockerfile
    depends_on:
      - bitcoind
    ports:
      - "8000:8000"
      - "8001:8001"

  evm-rpc-canister-proxy:
    container_name: evm-rpc-canister-proxy
    build:
      dockerfile: evm-rpc-canister-proxy.dockerfile
    ports:
      - "8002:8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  bitcoin-data:
